Film Star/Models/ErrorViewModel.cs
namespace Film_Star.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Film Star/Models/Film.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Film_Star.Models
{
	public class Film
	{
        public int Id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "You have to provide a valid Film Name.")]
        public string Name { get; set; }

        [DisplayName("Film Genres")]
        [Required(ErrorMessage = "You have to provide a valid Film Genres.")]
        public string Genres { get; set; }

        [DisplayName("Film Description")]
        [Required(ErrorMessage = "You have to provide a valid Film Description.")]
        public string Description { get; set; }

        [DisplayName("Film Duration")]
        [Required(ErrorMessage = "You have to provide a valid Film Duration.")]
        public int Duration { get; set; }

        [DisplayName("Image")]
        [ValidateNever]
        public string ImageURL { get; set; }

        public string Link { get; set; }


    }
}

Film Star/Controllers/FilmController.cs
using Film_Star.Data;
using Film_Star.Models;
using Microsoft.AspNetCore.Mvc;

namespace Film_Star.Controllers
{
	public class FilmController : Controller
	{

		ApplicationDbContext _context;
		IWebHostEnvironment _webHostEnvironment;

		public FilmController(IWebHostEnvironment webHostEnvironment, ApplicationDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_context = context;
		}

		[HttpGet]
		public IActionResult GetIndexView()
		{
			return View("Index", _context.films.ToList());
		}

		[HttpGet]
		public IActionResult GetAFlamView()
		{
			return View("AFlam", _context.films.ToList());
		}

		[HttpGet]
		public IActionResult GetDetailsView(int id)
		{
			Film film = _context.films.FirstOrDefault(e => e.Id == id);

			return View("Details", film);
		}

		[HttpGet]
		public IActionResult GetCreateView()
		{
			//ViewBag.DeptSelectItems = new SelectList(_context.Departments.ToList(), "Id", "Name");
			return View("Create");
		}

		[HttpPost]
		public IActionResult AddNew(Film film, IFormFile? imageFormFile) // FolanAlfolani.png
		{
			// GUID -> Globally Unique Identifier
			if (imageFormFile != null)
			{
				string imgExtension = Path.GetExtension(imageFormFile.FileName); // .png
				Guid imgGuid = Guid.NewGuid(); // xm789-f07li-624yn-uvx98
				string imgName = imgGuid + imgExtension; // xm789-f07li-624yn-uvx98.png
				string imgUrl = "\\Image\\" + imgName; //  \images\xm789-f07li-624yn-uvx98.png
				film.ImageURL = imgUrl;

				string imgPath = _webHostEnvironment.WebRootPath + imgUrl;

				// FileStream 
				FileStream imgStream = new FileStream(imgPath, FileMode.Create);
				imageFormFile.CopyTo(imgStream);
				imgStream.Dispose();
			}
			else
			{
				film.ImageURL = "\\Image\\No_Image.png";
			}

			if (ModelState.IsValid == true)
			{
				_context.films.Add(film);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				//ViewBag.DeptSelectItems = new SelectList(_context.Departments.ToList(), "Id", "Name");
				return View("Create");
			}
		}


		[HttpGet]
		public IActionResult GetEditView(int id)
		{
			Film film = _context.films.FirstOrDefault(e => e.Id == id);

			if (film == null)
			{
				return NotFound();
			}
			else
			{
				//ViewBag.DeptSelectItems = new SelectList(_context.Departments.ToList(), "Id", "Name");
				return View("Edit", film);
			}
		}


		[HttpPost]
		public IActionResult EditCurrent(Film film, IFormFile? imageFormFile)
		{
			// GUID -> Globally Unique Identifier
			if (imageFormFile != null)
			{
				if (film.ImageURL != "\\Image\\No_Image.png")
				{
					string oldImgPath = _webHostEnvironment.WebRootPath + film.ImageURL;

					if (System.IO.File.Exists(oldImgPath) == true)
					{
						System.IO.File.Delete(oldImgPath);
					}
				}


				string imgExtension = Path.GetExtension(imageFormFile.FileName); // .png
				Guid imgGuid = Guid.NewGuid(); // xm789-f07li-624yn-uvx98
				string imgName = imgGuid + imgExtension; // xm789-f07li-624yn-uvx98.png
				string imgUrl = "\\Image\\" + imgName; //  \images\xm789-f07li-624yn-uvx98.png
				film.ImageURL = imgUrl;

				string imgPath = _webHostEnvironment.WebRootPath + imgUrl;

				// FileStream 
				FileStream imgStream = new FileStream(imgPath, FileMode.Create);
				imageFormFile.CopyTo(imgStream);
				imgStream.Dispose();
			}


			if (ModelState.IsValid == true)
			{
				_context.films.Update(film);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				//ViewBag.DeptSelectItems = new SelectList(_context.Departments.ToList(), "Id", "Name");
				return View("Edit");
			}
		}


		[HttpGet]
		public IActionResult GetDeleteView(int id)
		{
			Film film = _context.films.FirstOrDefault(e => e.Id == id);

			if (film == null)
			{
				return NotFound();
			}
			else
			{
				return View("Delete", film);
			}
		}


		[HttpPost]
		public IActionResult DeleteCurrent(int id)
		{
			Film film = _context.films.FirstOrDefault(e => e.Id == id);
			if (film == null)
			{
				return NotFound();
			}
			else
			{
				if (film.ImageURL != "\\Image\\No_Image.png")
				{
					string imgPath = _webHostEnvironment.WebRootPath + film.ImageURL;

					if (System.IO.File.Exists(imgPath))
					{
						System.IO.File.Delete(imgPath);
					}
				}


				_context.films.Remove(film);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");

			}
		}
	}
}

Film Star/Controllers/HomeController.cs
using Film_Star.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Film_Star.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Film Star/Views/Film/AFlam.cshtml
@model IEnumerable<Film>

@if (Model.Count() > 0)
{
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@item.ImageURL" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">
                            @item.Duration min
                        </p>
                        <a href="@item.Link" class="btn btn-primary">Watch</a>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <h1 class="alert alert-danger text-center">There is no data.</h1>
}

Film Star/Views/Film/Delete.cshtml
@*
    Delete
*@
@model Film

<h1 class="alert alert-danger text-center">Are you sure you want to delete @Model.Name?</h1>

<div class="row">
    <dl class="row col-6">

        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e=>e.Name)</dt>
        <dd class="col-10">@Html.DisplayFor(e=>e.Name)</dd>
        @*<dd class="col-10">@Model.Name</dd>*@
        
        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e => e.Genres)</dt>
        <dd class="col-10">@Html.DisplayFor(e => e.Genres)</dd>
        @*<dd class="col-10">@Model.Genres</dd>*@

        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e=> e.Description)</dt>
        <dd class="col-10">@Html.DisplayFor(e=> e.Description)</dd>
        @*<dd class="col-10">@Model.Description</dd>*@
       
        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e=>e.Duration)</dt>
        <dd class="col-10">@Html.DisplayFor(e=>e.Duration)</dd>
        @*<dd class="col-10">@Model.Duration</dd>*@

        <br />
        <hr />

    </dl>

    <div class="col-6">
        <img src="@Model.ImageURL" style="width:50%;aspect-ratio:1/1" />
    </div>
</div>

<form method="post" asp-controller="Film" asp-action="DeleteCurrent">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

<a asp-controller="Film" asp-action="GetIndexView">Back to List</a>

Film Star/Views/Film/Details.cshtml
@*
    Details
*@
@model Film

<h1 class="alert alert-info text-center">@Model.Name Details</h1>

<div class="row">
    <hr />
    <dl class="row col-8">
        
        <dt class="col-2">@Html.DisplayNameFor(e=>e.Name)</dt>
        <dd class="col-10">@Html.DisplayFor(e=>e.Name)</dd>
        @*<dd class="col-10">@Model.Name</dd>*@

        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e=> e.Genres)</dt>
        <dd class="col-10">@Html.DisplayFor(e=> e.Genres)</dd>
        @*<dd class="col-10">@Model.Genres</dd>*@

        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e => e.Description)</dt>
        <dd class="col-10">@Html.DisplayFor(e => e.Description)</dd>
        @*<dd class="col-10">@Model.Description</dd>*@

        <br />
        <hr />

        <dt class="col-2">@Html.DisplayNameFor(e=>e.Duration)</dt>
        <dd class="col-10">@Html.DisplayFor(e=>e.Duration) min</dd>
        @*<dd class="col-10">@Model.Duration</dd>*@

    </dl>
   

    <div class="col-4">
        <img src="@Model.ImageURL" style="width:80%;aspect-ratio:1/1" />
    </div>

</div>
<div class="text-center">
    <button onclick="redirectToLink()" class="btn btn-success">Watch</button>
</div>
<a asp-controller="Film" asp-action="GetIndexView">Back to List</a>



<script>
    function redirectToLink() {
      var link = "@Model.Link";
      window.location.href = link;
    }
</script>

<hr />
        <br />
        <br />
        

Film Star/Views/Film/Edit.cshtml
@*
    Edit
*@
@model Film

<h1 class="alert alert-warning text-center">
    Edit @Model.Name Info
</h1>

<div class="row">
    <form class="col-4" method="post" asp-controller="Film" asp-action="EditCurrent" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ImageURL" />

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Name)</label>*@
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Genres)</label>*@
            <label asp-for="Genres"></label>
            <input type="text" asp-for="Genres" class="form-control" />
            <span asp-validation-for="Genres" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Description)</label>*@
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control">Description</textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Duration)</label>*@
            <label asp-for="Duration"></label>
            <input asp-for="Duration" class="form-control" />
            <span asp-validation-for="Duration" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="ImageURL"></label>
            <input type="file" name="imageFormFile" id="imageFormFile" accept=".png,.jpg" onchange="AddImage()" class="form-control" />
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Link)</label>*@
            <label asp-for="Link"></label>
            <input type="text" asp-for="Link" class="form-control" />
            <span asp-validation-for="Link" class="text-danger"></span>
        </div>

        <div>
            <button type="submit" class="btn btn-primary mt-1">Edit</button>
            <a asp-controller="Film" asp-action="GetIndexView">Back to List</a>
        </div>
    </form>

    <div class="col-4">
        <img src="@Model.ImageURL" id="FilmImage" style="object-fit:contain" />
    </div>


</div>

@section Scripts{
    <script>
        function AddImage() {
            document.getElementById('FilmImage').src = window.URL.createObjectURL(document.getElementById('imageFormFile').files[0]);
        }
    </script>
}

Film Star/Views/Film/Index.cshtml
@*
    Index
*@
@model IEnumerable<Film>

<h1 class="alert alert-info text-center">
    Films List
</h1>

<a asp-controller="Film" asp-action="GetCreateView" class="btn btn-success mb-1">
    Add New Film
</a>


@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(e=>e.Name)</th>
                <th>@Html.DisplayNameFor(e=>e.Genres)</th>
                <th>@Html.DisplayNameFor(e=>e.Duration)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Genres</td>
                    <td>@item.Duration min</td>
                    <td>
                        <a asp-controller="Film" asp-action="GetDetailsView"
                           asp-route-id="@item.Id" class="btn btn-outline-success" title="Details"><i class="bi bi-list-ul"></i></a>

                        <a asp-controller="Film" asp-action="GetEditView"
                           asp-route-id="@item.Id" class="btn btn-outline-primary" title="Edit"><i class="bi bi-pencil-square"></i></a>

                        <a asp-controller="Film" asp-action="GetDeleteView"
                           asp-route-id="@item.Id" class="btn btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1 class="alert alert-danger text-center">There is no data.</h1>
}

<br />
<hr />
<br />

Film Star/Views/Film/create.cshtml
@*
    Create
*@
@model Film

<h1 class="alert alert-warning text-center">
    Add New Film
</h1>

<div class="row">
    <form class="col-4" method="post" asp-controller="Film" asp-action="AddNew" enctype="multipart/form-data">

        <div asp-validation-summary="All" class="text-danger"></div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Name)</label>*@
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Genres)</label>*@
            <label asp-for="Genres"></label>
            <input type="text" asp-for="Genres" class="form-control" />
            <span asp-validation-for="Genres" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Description)</label>*@
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control">Description</textarea>
            @*<input type="text" asp-for="Description" class="form-control" />*@
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Duration)</label>*@
            <label asp-for="Duration"></label>
            <input asp-for="Duration" class="form-control" />
            <span asp-validation-for="Duration" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="ImageURL"></label>
            <input type="file" name="imageFormFile" id="imageFormFile"
                                 accept=".png,.jpg" onchange="AddImage()" class="form-control" />
            <span asp-validation-for="ImageURL"></span>
        </div>

        <div>
            @*<label>@Html.DisplayNameFor(e=>e.Duration)</label>*@
            <label asp-for="Link"></label>
            <input asp-for="Link" class="form-control" />
            <span asp-validation-for="Link" class="text-danger"></span>
        </div>

        <div>
            <button type="submit" class="btn btn-primary mt-1">Add</button>
            <a asp-controller="Employees" asp-action="GetIndexView">Back to List</a>
        </div>
    </form>

    <div class="col-4">
        <img src="" id="FilmImage" style="object-fit:contain" />
    </div>

</div>


@section Scripts{
    <script>
        function AddImage() {
            document.getElementById('FilmImage').src = window.URL.createObjectURL(document.getElementById('imageFormFile').files[0]);
        }
    </script>
}

Film Star/Views/Home/Index.cshtml
<!DOCTYPE>
<html>
    <head>
        <title>FilmStar</title>
    </head>
    <body>
        <hr />
    <h1 class="text-center">Welcome to FilmStar</h1>
    
    @*<div width="100%" height="100%" class="">
        .<img src="/Image/Home-BackGround.jpg" />
    </div>*@

    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/Image/BG1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/Image/BG2.jpg" alt="Second slide">
            </div>
        </div>
    </div>

    </body>
</html>

Film Star/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Film_Star</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Film_Star.styles.css" asp-append-version="true" />
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FilmStar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Film" asp-action="GetIndexView">Film List</a>
                        </li>
                        <li>
                            <a class="nav-link text-light" asp-area="" asp-controller="Film" asp-action="GetAFlamView">AFilmy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Film_Star - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>